version: '3.4'

services:
  provaeclipseworks:
    image: ${DOCKER_REGISTRY-}provaeclipseworks
    build:
      context: .
      dockerfile: prova-eclipseworks/Dockerfile
    ports:
     - "8081:80"       
    depends_on:
     - eclipseData

  eclipseData:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Eclipse123@
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"  